
<?$APPLICATION->IncludeComponent(
	"bitrix:news.list",
	"docs",
	array(
		"IBLOCK_TYPE"	=>	$arResult['PARENT']->arParams["IBLOCK_TYPE"],
		"IBLOCK_ID"	=>	$arResult['PARENT']->arParams["IBLOCK_ID"],
		"NEWS_COUNT"	=>	$arResult['PARENT']->arParams["NEWS_COUNT"],
		"SORT_BY1"	=>	$arResult['PARENT']->arParams["SORT_BY1"],
		"SORT_ORDER1"	=>	$arResult['PARENT']->arParams["SORT_ORDER1"],
		"SORT_BY2"	=>	$arResult['PARENT']->arParams["SORT_BY2"],
		"SORT_ORDER2"	=>	$arResult['PARENT']->arParams["SORT_ORDER2"],
		"FIELD_CODE"	=>	$arResult['PARENT']->arParams["LIST_FIELD_CODE"],
		"PROPERTY_CODE"	=>	$arResult['PARENT']->arParams["LIST_PROPERTY_CODE"],
		"DETAIL_URL"	=>	$arResult["FOLDER"].$arResult["URL_TEMPLATES"]["detail"],
		"DISPLAY_PANEL"	=>	$arResult['PARENT']->arParams["DISPLAY_PANEL"],
		"SET_TITLE"	=>	$arResult['PARENT']->arParams["SET_TITLE"],
		"SET_STATUS_404" => $arResult['PARENT']->arParams["SET_STATUS_404"],
		"INCLUDE_IBLOCK_INTO_CHAIN"	=>	$arResult['PARENT']->arParams["INCLUDE_IBLOCK_INTO_CHAIN"],
		"CACHE_TYPE"	=>	$arResult['PARENT']->arParams["CACHE_TYPE"],
		"CACHE_TIME"	=>	$arResult['PARENT']->arParams["CACHE_TIME"],
		"CACHE_FILTER"	=>	$arResult['PARENT']->arParams["CACHE_FILTER"],
		"CACHE_GROUPS" => $arResult['PARENT']->arParams["CACHE_GROUPS"],
		"DISPLAY_TOP_PAGER"	=>	$arResult['PARENT']->arParams["DISPLAY_TOP_PAGER"],
		"DISPLAY_BOTTOM_PAGER"	=>	$arResult['PARENT']->arParams["DISPLAY_BOTTOM_PAGER"],
		"PAGER_TITLE"	=>	$arResult['PARENT']->arParams["PAGER_TITLE"],
		"PAGER_TEMPLATE"	=>	$arResult['PARENT']->arParams["PAGER_TEMPLATE"],
		"PAGER_SHOW_ALWAYS"	=>	$arResult['PARENT']->arParams["PAGER_SHOW_ALWAYS"],
		"PAGER_DESC_NUMBERING"	=>	$arResult['PARENT']->arParams["PAGER_DESC_NUMBERING"],
		"PAGER_DESC_NUMBERING_CACHE_TIME"	=>	$arResult['PARENT']->arParams["PAGER_DESC_NUMBERING_CACHE_TIME"],
		"PAGER_SHOW_ALL" => $arResult['PARENT']->arParams["PAGER_SHOW_ALL"],
		"DISPLAY_DATE"	=>	$arResult['PARENT']->arParams["DISPLAY_DATE"],
		"DISPLAY_NAME"	=>	$arResult['PARENT']->arParams["DISPLAY_NAME"],
		"DISPLAY_PICTURE"	=>	$arResult['PARENT']->arParams["DISPLAY_PICTURE"],
		"DISPLAY_PREVIEW_TEXT"	=>	$arResult['PARENT']->arParams["DISPLAY_PREVIEW_TEXT"],
		"PREVIEW_TRUNCATE_LEN"	=>	$arResult['PARENT']->arParams["PREVIEW_TRUNCATE_LEN"],
		"ACTIVE_DATE_FORMAT"	=>	$arResult['PARENT']->arParams["LIST_ACTIVE_DATE_FORMAT"],
		"USE_PERMISSIONS"	=>	$arResult['PARENT']->arParams["USE_PERMISSIONS"],
		"GROUP_PERMISSIONS"	=>	$arResult['PARENT']->arParams["GROUP_PERMISSIONS"],
		"FILTER_NAME"	=>	$arResult['PARENT']->arParams["FILTER_NAME"],
		"HIDE_LINK_WHEN_NO_DETAIL"	=>	$arResult['PARENT']->arParams["HIDE_LINK_WHEN_NO_DETAIL"],
		"CHECK_DATES"	=>	$arResult['PARENT']->arParams["CHECK_DATES"],
		"COMPONENT_TEMPLATE" => $arResult['PARENT']->arParams["COMPONENT_TEMPLATE"],

		"PARENT_SECTION_CODE" => $arResult['PARENT']->arParams["PARENT_SECTION_CODE"],
		"LOG_PAGE_URL" => $arResult['PARENT']->arParams['SEF_FOLDER'] . $arResult['PARENT']->arParams['SEF_URL_TEMPLATES']['detail']
	),
	false
);?>