
<? $APPLICATION->IncludeComponent(
	"citrus:smartform.iblock.form", 
	"simple",
	array(
		"AFTER_FORM_TOOLTIP" => "",
		"AJAX" => "Y",
		"ANCHOR_ID" => "",
		"BEFORE_FORM_TOOLTIP" => "",
		"BUTTON_POSITION" => "CENTER",
		"BUTTON_TITLE" => "",
		"COMPONENT_TEMPLATE" => ".default",
		"EDIT_ELEMENT" => "N",
		"ELEMENT_ID" => "",
		"ERROR_TEXT" => "",
		"FIELDS" => array(
			"PROPERTY_href" => array(
				"TITLE" => "Отправлено со страницы",
				"IS_REQUIRED" => "N",
				"HIDE_FIELD" => "Y",
				"ORIGINAL_TITLE" => "[54] Отправлено со страницы",
				"DEFAULT" => Citrus\Developer\Helper::getPath(),
			),
			"PROPERTY_ITEMS" => array(
				"TITLE" => "Услуга",
				"IS_REQUIRED" => "N",
				"HIDE_FIELD" => "Y",
				"ORIGINAL_TITLE" => "[53] Услуга",
				"DEFAULT" => $arParams["SERVICE_ID"],
			),
			"group_1493898921502" => array(
				"ORIGINAL_TITLE" => "Новая группа (group_1493898921502)",
				"TITLE" => "Новая группа",
				"GROUP_FIELD" => "Y",
				"DEPTH_LAVEL" => "1",
				"CLASS" => "row-ib",
				"IS_REQUIRED" => "N",
				"HIDE_FIELD" => "N",
			),
			"group_1493898928264" => array(
				"ORIGINAL_TITLE" => "Новая группа (group_1493898928264)",
				"TITLE" => "Новая группа",
				"GROUP_FIELD" => "Y",
				"DEPTH_LAVEL" => "2",
				"CLASS" => "col-md-6",
				"IS_REQUIRED" => "N",
				"HIDE_FIELD" => "N",
			),
			"NAME" => array(
				"ORIGINAL_TITLE" => "Название",
				"TITLE" => "Ваше имя",
				"IS_REQUIRED" => "Y",
				"HIDE_FIELD" => "N",
			),
			"PROPERTY_phone" => array(
				"TITLE" => "Телефон",
				"IS_REQUIRED" => "Y",
				"HIDE_FIELD" => "N",
				"ORIGINAL_TITLE" => "[55] Телефон",
				"TEMPLATE_ID" => "phone",
				"VALIDRULE" => "phone",
			),
			"PROPERTY_email" => array(
				"TITLE" => "Email",
				"IS_REQUIRED" => "Y",
				"HIDE_FIELD" => "N",
				"ORIGINAL_TITLE" => "[56] Email",
				"VALIDRULE" => "email",
			),
			"group_1493898937831" => array(
				"ORIGINAL_TITLE" => "Новая группа (group_1493898937831)",
				"TITLE" => "Новая группа",
				"GROUP_FIELD" => "Y",
				"DEPTH_LAVEL" => "2",
				"CLASS" => "col-md-6",
				"IS_REQUIRED" => "N",
				"HIDE_FIELD" => "N",
			),
			"PREVIEW_TEXT" => array(
				"ORIGINAL_TITLE" => "Описание для анонса",
				"TITLE" => "Текст сообщения",
				"IS_REQUIRED" => "N",
				"HIDE_FIELD" => "N",
			),
		),
		"FORM_ID" => "68fe236acbcb7d2e4034a68d2fc9bc76",
		"FORM_STYLE" => "GRAY",
		"FORM_TITLE" => "Написать нам",
		"IBLOCK_ID" => "",
		"IBLOCK_TYPE" => "feedback",
		"IBLOCK_CODE" => "requests",
		"JQUERY_VALID" => "Y",
		"NOT_CREATE_ELEMENT" => "N",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"REDIRECT_AFTER_SUCCESS" => "N",
		"SAVE_SESSION" => "Y",
		"SEND_MESSAGE" => "Y",
		"MAIL_EVENT" => "CITRUS_REALTY_NEW_REQUEST",
		"SUB_TEXT" => "",
		"SUCCESS_TEXT" => "Сообщение успешно отправлено",
		"USER_SERVER_VALIDATE" => "N",
		"USE_SERVER_VALIDATE" => "N",
		"AGREEMENT_LINK" => "/agreement/",
		"USE_GOOGLE_RECAPTCHA" => "N",
		"HIDDEN_ANTI_SPAM" => "Y"
	),
	false
);?>
